"""empty message

Revision ID: 29d4d9204cee
Revises: e0cb90f85c8a
Create Date: 2018-04-03 16:12:46.195051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d4d9204cee'
down_revision = 'e0cb90f85c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('RoleType', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'RoleType')
    # ### end Alembic commands ###
