"""empty message

Revision ID: f87aa97231e0
Revises: 
Create Date: 2018-04-03 16:10:06.738281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87aa97231e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserCode', sa.String(length=64), nullable=True),
    sa.Column('Password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_UserCode'), 'users', ['UserCode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_UserCode'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
